[project]
name = "homeworky-web"
version = "0.1.0"
description = "Homeworky Web Application"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "sqlmodel",
    "alembic",
    "psycopg2-binary",
    "pydantic-settings",
    "python-dotenv",
    "python-multipart",
    "sqladmin",
    "jinja2",
    "aiofiles",
    "itsdangerous",
    "bcrypt",
    "uvicorn",
]

[tool.setuptools]
packages = ["app"]

[tool.fastapi]
entrypoint = "app.main:app"
