"""added user agents field to both session models

Revision ID: 0fccb8c99844
Revises: 20076d64990d
Create Date: 2026-08-25 12:03:04.159977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0fccb8c99844'
down_revision: Union[str, Sequence[str], None] = '20076d64990d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classsession', sa.Column('raw_user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('classsession', sa.Column('device_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('classsession', sa.Column('device_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('classsession', sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('classsession', sa.Column('os_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('classsession', sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('classsession', sa.Column('browser_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('classsession', sa.Column('browser_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('classsession', sa.Column('is_mobile', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('classsession', sa.Column('is_tablet', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('classsession', sa.Column('is_pc', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('classsession', sa.Column('is_bot', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('classsession', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_classsession_browser_family'), 'classsession', ['browser_family'], unique=False)
    op.create_index(op.f('ix_classsession_device_family'), 'classsession', ['device_family'], unique=False)
    op.create_index(op.f('ix_classsession_os_family'), 'classsession', ['os_family'], unique=False)
    op.create_index(op.f('ix_classsession_raw_user_agent'), 'classsession', ['raw_user_agent'], unique=False)
    op.add_column('staffsession', sa.Column('raw_user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staffsession', sa.Column('device_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staffsession', sa.Column('device_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staffsession', sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staffsession', sa.Column('os_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staffsession', sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staffsession', sa.Column('browser_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staffsession', sa.Column('browser_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staffsession', sa.Column('is_mobile', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('staffsession', sa.Column('is_tablet', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('staffsession', sa.Column('is_pc', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('staffsession', sa.Column('is_bot', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('staffsession', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_staffsession_browser_family'), 'staffsession', ['browser_family'], unique=False)
    op.create_index(op.f('ix_staffsession_device_family'), 'staffsession', ['device_family'], unique=False)
    op.create_index(op.f('ix_staffsession_os_family'), 'staffsession', ['os_family'], unique=False)
    op.create_index(op.f('ix_staffsession_raw_user_agent'), 'staffsession', ['raw_user_agent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staffsession_raw_user_agent'), table_name='staffsession')
    op.drop_index(op.f('ix_staffsession_os_family'), table_name='staffsession')
    op.drop_index(op.f('ix_staffsession_device_family'), table_name='staffsession')
    op.drop_index(op.f('ix_staffsession_browser_family'), table_name='staffsession')
    op.drop_column('staffsession', 'created_at')
    op.drop_column('staffsession', 'is_bot')
    op.drop_column('staffsession', 'is_pc')
    op.drop_column('staffsession', 'is_tablet')
    op.drop_column('staffsession', 'is_mobile')
    op.drop_column('staffsession', 'browser_version')
    op.drop_column('staffsession', 'browser_family')
    op.drop_column('staffsession', 'os_version')
    op.drop_column('staffsession', 'os_family')
    op.drop_column('staffsession', 'device_model')
    op.drop_column('staffsession', 'device_brand')
    op.drop_column('staffsession', 'device_family')
    op.drop_column('staffsession', 'raw_user_agent')
    op.drop_index(op.f('ix_classsession_raw_user_agent'), table_name='classsession')
    op.drop_index(op.f('ix_classsession_os_family'), table_name='classsession')
    op.drop_index(op.f('ix_classsession_device_family'), table_name='classsession')
    op.drop_index(op.f('ix_classsession_browser_family'), table_name='classsession')
    op.drop_column('classsession', 'created_at')
    op.drop_column('classsession', 'is_bot')
    op.drop_column('classsession', 'is_pc')
    op.drop_column('classsession', 'is_tablet')
    op.drop_column('classsession', 'is_mobile')
    op.drop_column('classsession', 'browser_version')
    op.drop_column('classsession', 'browser_family')
    op.drop_column('classsession', 'os_version')
    op.drop_column('classsession', 'os_family')
    op.drop_column('classsession', 'device_model')
    op.drop_column('classsession', 'device_brand')
    op.drop_column('classsession', 'device_family')
    op.drop_column('classsession', 'raw_user_agent')
    # ### end Alembic commands ###
