"""added client_ip field to sessions

Revision ID: 949d1ffdf08d
Revises: 0fccb8c99844
Create Date: 2026-08-26 16:35:02.993643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '949d1ffdf08d'
down_revision: Union[str, Sequence[str], None] = '0fccb8c99844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classsession', sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staffsession', sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffsession', 'client_ip')
    op.drop_column('classsession', 'client_ip')
    # ### end Alembic commands ###
