"""initial schema

Revision ID: d3115520050b
Revises: 
Create Date: 2026-08-24 12:20:41.116919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3115520050b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_name'), 'class', ['name'], unique=False)
    op.create_table('classsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classsession_class_id'), 'classsession', ['class_id'], unique=False)
    op.create_index(op.f('ix_classsession_token_hash'), 'classsession', ['token_hash'], unique=False)
    op.create_table('homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_class_id'), 'homework', ['class_id'], unique=False)
    op.create_table('staffmember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staffmember_username'), 'staffmember', ['username'], unique=True)
    op.create_table('staffsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staffmember.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staffsession_staff_member_id'), 'staffsession', ['staff_member_id'], unique=False)
    op.create_index(op.f('ix_staffsession_token_hash'), 'staffsession', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staffsession_token_hash'), table_name='staffsession')
    op.drop_index(op.f('ix_staffsession_staff_member_id'), table_name='staffsession')
    op.drop_table('staffsession')
    op.drop_index(op.f('ix_staffmember_username'), table_name='staffmember')
    op.drop_table('staffmember')
    op.drop_index(op.f('ix_homework_class_id'), table_name='homework')
    op.drop_table('homework')
    op.drop_index(op.f('ix_classsession_token_hash'), table_name='classsession')
    op.drop_index(op.f('ix_classsession_class_id'), table_name='classsession')
    op.drop_table('classsession')
    op.drop_index(op.f('ix_class_name'), table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###
