"""migration1

Revision ID: d8f1c4202fee
Revises: e35dc8e6d293
Create Date: 2026-08-30 14:55:26.093607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8f1c4202fee'
down_revision: Union[str, Sequence[str], None] = 'e35dc8e6d293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appsession_browser_family'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_class_id_db'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_device_family'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_os_family'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_raw_user_agent'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_staff_id_db'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_token_hash'), table_name='appsession')
    op.drop_table('appsession')
    op.add_column('staff', sa.Column('is_mod', sa.Boolean(), nullable=False))
    op.drop_column('staff', 'is_moderator')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('is_moderator', sa.BOOLEAN(), nullable=False))
    op.drop_column('staff', 'is_mod')
    op.create_table('appsession',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), nullable=False),
    sa.Column('staff_id_db', sa.INTEGER(), nullable=True),
    sa.Column('class_id_db', sa.INTEGER(), nullable=True),
    sa.Column('raw_user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('device_family', sa.VARCHAR(), nullable=True),
    sa.Column('device_brand', sa.VARCHAR(), nullable=True),
    sa.Column('device_model', sa.VARCHAR(), nullable=True),
    sa.Column('client_ip', sa.VARCHAR(), nullable=True),
    sa.Column('os_family', sa.VARCHAR(), nullable=True),
    sa.Column('os_version', sa.VARCHAR(), nullable=True),
    sa.Column('browser_family', sa.VARCHAR(), nullable=True),
    sa.Column('browser_version', sa.VARCHAR(), nullable=True),
    sa.Column('is_mobile', sa.BOOLEAN(), nullable=False),
    sa.Column('is_tablet', sa.BOOLEAN(), nullable=False),
    sa.Column('is_pc', sa.BOOLEAN(), nullable=False),
    sa.Column('is_bot', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['class_id_db'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id_db'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appsession_token_hash'), 'appsession', ['token_hash'], unique=1)
    op.create_index(op.f('ix_appsession_staff_id_db'), 'appsession', ['staff_id_db'], unique=False)
    op.create_index(op.f('ix_appsession_raw_user_agent'), 'appsession', ['raw_user_agent'], unique=False)
    op.create_index(op.f('ix_appsession_os_family'), 'appsession', ['os_family'], unique=False)
    op.create_index(op.f('ix_appsession_device_family'), 'appsession', ['device_family'], unique=False)
    op.create_index(op.f('ix_appsession_class_id_db'), 'appsession', ['class_id_db'], unique=False)
    op.create_index(op.f('ix_appsession_browser_family'), 'appsession', ['browser_family'], unique=False)
    # ### end Alembic commands ###
