"""initial_schema

Revision ID: e35dc8e6d293
Revises: 
Create Date: 2026-08-28 16:58:04.833013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e35dc8e6d293'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_name'), 'class', ['name'], unique=False)
    op.create_table('homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_id_db', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id_db'], ['class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_class_id_db'), 'homework', ['class_id_db'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_moderator', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('class_id_db', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id_db'], ['class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_class_id_db'), 'staff', ['class_id_db'], unique=False)
    op.create_index(op.f('ix_staff_username'), 'staff', ['username'], unique=True)
    op.create_table('appsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('staff_id_db', sa.Integer(), nullable=True),
    sa.Column('class_id_db', sa.Integer(), nullable=True),
    sa.Column('raw_user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('os_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('browser_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('browser_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_mobile', sa.Boolean(), nullable=False),
    sa.Column('is_tablet', sa.Boolean(), nullable=False),
    sa.Column('is_pc', sa.Boolean(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id_db'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id_db'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appsession_browser_family'), 'appsession', ['browser_family'], unique=False)
    op.create_index(op.f('ix_appsession_class_id_db'), 'appsession', ['class_id_db'], unique=False)
    op.create_index(op.f('ix_appsession_device_family'), 'appsession', ['device_family'], unique=False)
    op.create_index(op.f('ix_appsession_os_family'), 'appsession', ['os_family'], unique=False)
    op.create_index(op.f('ix_appsession_raw_user_agent'), 'appsession', ['raw_user_agent'], unique=False)
    op.create_index(op.f('ix_appsession_staff_id_db'), 'appsession', ['staff_id_db'], unique=False)
    op.create_index(op.f('ix_appsession_token_hash'), 'appsession', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appsession_token_hash'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_staff_id_db'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_raw_user_agent'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_os_family'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_device_family'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_class_id_db'), table_name='appsession')
    op.drop_index(op.f('ix_appsession_browser_family'), table_name='appsession')
    op.drop_table('appsession')
    op.drop_index(op.f('ix_staff_username'), table_name='staff')
    op.drop_index(op.f('ix_staff_class_id_db'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_homework_class_id_db'), table_name='homework')
    op.drop_table('homework')
    op.drop_index(op.f('ix_class_name'), table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###
